### ISSUE TITLE
General ToDo

### ISSUE THREAD

**Issue by lswainemoore** [dherg/yamtorrent#4]
- [ ] DO WRITEUP
- [ ] Be in contact with tracker
  - [ ] Get more peers (maintain unique list)
  - [ ] Let it know what we have 
- [ ] Seeding
  - [ ] Send out bitfields/haves
  - [ ] unchoke people
  - [ ] send pieces
- [x] Quit with a peer connection if it's taking too long (timeout)
- [x] Request same piece from multiple peers (endgame), cancels when receive one
  - [x] would need to change requests dictionary format to accomplish this
- [x] pick a smarter way to prioritize pieces than order?

**Comment by dherg** [comment]
- [ ] UDP tracker support
- [x] Remove .part from filename when download complete
- [ ] Handle multi-file torrents
